apiVersion: v2
appVersion: 1.25.01
version: 20.3.10
dependencies:
  - name: common
    version: 28.29.17
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: FreshRSS is a self-hosted RSS feed aggregator
home: https://truecharts.org/charts/stable/freshrss
icon: https://truecharts.org/img/hotlink-ok/chart-icons/freshrss.webp
keywords:
  - freshrss
  - rss
kubeVersion: ">=1.24.0-0"
name: freshrss
sources:
  - https://ghcr.io/linuxserver/freshrss
  - https://github.com/FreshRSS/FreshRSS
  - https://github.com/truecharts/charts/tree/master/charts/stable/freshrss
type: application
