image:
  repository: ghcr.io/linuxserver/freshrss
  pullPolicy: IfNotPresent
  tag: 1.24.3@sha256:51ab93c927d3b178e4550f33f7b02cd61acb9854cff4af6e1e66f8058fff3a60
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  # nodeport:
  #   enabled: true
  #   type: NodePort
  #   ports:
  #     node-port-name:
  #       enabled: true
  #       port: 80
  #       targetPort: 80
  #       nodePort: 30088
  main:
    # service-lb:
    #   enabled: true
    #   primary: true
    #   type: LoadBalancer
    #   loadBalancerIP: 192.168.4.222
    ports:
      main:
        port: 8888
        targetPort: 80
        protocol: tcp
        name: http
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true