apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rag.fullname" $ | lower}}-config
data:
  POSTGRES_DB: {{ .Values.postgresql.auth.database }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username }}
  DB_HOST: {{ .Values.postgresql.auth.dbhost }}
  {{- toYaml .Values.rag.configEnv | nindent 2 }} 