apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rag.fullname" $ | lower}}-config
data:
  POSTGRES_DB: {{ .Values.postgresql.auth.database }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username }}
  DB_HOST: librechat-rag-api-postgresql.flux-system.svc.buran-kube.local
  {{- toYaml .Values.rag.configEnv | nindent 2 }} 