---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
data:
  soju.conf: |
    listen {{ .Values.config.listen }}
    listen unix+admin:///var/lib/soju/admin.sock
    hostname {{ .Values.config.hostname }}
    title {{ .Values.config.title }}
    db sqlite3 /var/lib/soju/soju.db
    message-store {{ .Values.config.messageStore }}
