apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: freshrss
  name: freshrss-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: tcp
      port: http
      targetPort: http
  selector:
    app.kubernetes.io/instance: freshrss
    