apiVersion: v1
kind: Service
metadata:
  name: {{ include "xray-proxy.fullname" . }}
  labels:
    {{- include "xray-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.socks5Port }}
      targetPort: socks5
      protocol: TCP
      name: socks5
    - port: {{ .Values.service.realityPort }}
      targetPort: reality
      protocol: TCP
      name: reality
    {{- if .Values.monitoring.enabled }}
    - port: {{ .Values.monitoring.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "xray-proxy.selectorLabels" . | nindent 4 }}