apiVersion: v1
kind: Service
metadata:
  name: {{ include "xray-proxy.fullname" . }}
  labels:
    {{- include "xray-proxy.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- range .Values.service.loadBalancerSourceRanges }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- if and (eq .Values.service.type "ClusterIP") .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
    {{- range .Values.service.externalIPs }}
    - {{ . }}
    {{- end }}
  {{- end }}
  ports:
    {{- if .Values.xray.socks5.enabled }}
    - port: {{ .Values.service.socks5Port | default .Values.xray.socks5.port }}
      targetPort: socks5
      protocol: TCP
      name: socks5
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.socks5NodePort }}
      nodePort: {{ .Values.service.socks5NodePort }}
      {{- end }}
    {{- end }}
    {{- if .Values.xray.reality.enabled }}
    - port: {{ .Values.service.realityPort | default .Values.xray.reality.port }}
      targetPort: vless-reality
      protocol: TCP
      name: vless-reality
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.realityNodePort }}
      nodePort: {{ .Values.service.realityNodePort }}
      {{- end }}
    {{- end }}
    {{- if .Values.monitoring.enabled }}
    - port: {{ .Values.monitoring.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "xray-proxy.selectorLabels" . | nindent 4 }}