apiVersion: v2
name: filebrowser
description: A Helm chart for the File Browser project
type: application
version: 1.0.5
appVersion: v2.36.3
home: https://filebrowser.org
keywords:
  - filebrowser
  - file-browser
  - file-server
  - http-file-server
sources:
  - https://github.com/filebrowser/filebrowser
annotations:
  artifacthub.io/license: MIT
